name: Close PR by deadline and slack notification
on:
  schedule:
  - cron: '*/10 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get random issue gacha
        uses: matometaru/pr-deadline@v0.0.1
        with:
          token: ${{ secrets.LGTM_TOKEN }}
        id: prDeadline
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: self
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: format('Closed: {0}', toJson(steps.prDeadline.outputs.closedPulls).*.htmlUrl)
          SLACK_TITLE: 'pr-deadline'
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
