name: Close PR by deadline and slack notification
on:
  schedule:
  - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Close PR by deadline
        uses: matometaru/pr-deadline@0.1.2
        with:
          token: ${{ secrets.PR_TOKEN }}
          expirationDate: -1
        id: prDeadline
      - name: Slack Notification
        if: steps.prDeadline.outputs.closedPulls != '[]'
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: self
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ${{ steps.prDeadline.outputs.message }}
          SLACK_TITLE: pr-deadline
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
