name: Get Issue and slack notification
on: [issues]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue
        uses: matometaru/sample-action@v1.1.5
        with:
          labels: "test"
        id: sample
      - name: Echo the greeting's title
        run: echo 'The time was ${{ steps.sample.outputs.title }}.'
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: self
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket: ${{ steps.sample.outputs.htmlUrl }}'
          SLACK_TITLE: ${{ steps.sample.outputs.time }}
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
